version: "3.9"

services:
  postgres:
    container_name: pg-db
    image: postgres
    networks:
      - bridge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    networks:
      - bridge
    environment:
      PGADMIN_DEFAULT_EMAIL: ag@ag.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5051:443"
      - "5050:80"
    volumes:
      - "./pgadata:/var/lib/pgadmin"
    restart: always

volumes:
  pgadata:
  pgdata:

networks:
   bridge:
     driver: bridge